
#binlog position flush到磁盘的间隔
binlog_flush_ms = 2000  #2s刷新一次


[clusters]
agents = ["10.10.106.40:20600"]

[log]
log_path = "log/producer.log"
# 0 单个文件 1按天分 2按小时分
type = 2
highlighting = false
level = "info"

#定义订阅的mysql主库的连接信息
[[mysql]]
id = "1"
addr = "10.10.106.70:3306"
user = "inception"
password = "inception"
flavor = "mysql"  
data_path = "./conf/master1.info"
nsname = "ns1"
tablename = "table1"


 
